// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imdbtests.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the ImdbTests module
	public static void getImdbNames(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbNames").withParams(params).execute(context);
	}
	public static void getImdbTitleAkas(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbTitleAkas").withParams(params).execute(context);
	}
	public static void getImdbTitleBasics(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbTitleBasics").withParams(params).execute(context);
	}
	public static void getImdbTitleCrew(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbTitleCrew").withParams(params).execute(context);
	}
	public static void getImdbTitleEpisodes(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbTitleEpisodes").withParams(params).execute(context);
	}
	public static void getImdbTitlePrincipals(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbTitlePrincipals").withParams(params).execute(context);
	}
	public static void getImdbTitleRatings(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.GetImdbTitleRatings").withParams(params).execute(context);
	}
	public static void importAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.ImportAll").withParams(params).execute(context);
	}
	public static void truncateTables(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImdbTests.TruncateTables").withParams(params).execute(context);
	}
}
