// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imdbtests.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ImdbTests module

	public static java.lang.Long getIMPORT_OBJECT_MAX()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("ImdbTests.IMPORT_OBJECT_MAX");
	}
}