// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvservices.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import csvservices.impl.CsvExporter;
import csvservices.impl.CsvServicesImpl;
import java.io.ByteArrayInputStream;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;

public class ExportCsvData extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Entity;
	private java.lang.String Delimiter;

	public ExportCsvData(IContext context, java.lang.String Entity, java.lang.String Delimiter)
	{
		super(context);
		this.Entity = Entity;
		this.Delimiter = Delimiter;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info("executeAction: " + this.Entity + ", " + Arrays.toString(this.Entity.split("\\.")));
        if (this.Delimiter == null){
        	this.Delimiter = ",";
		}
        CsvExporter csvExporter = new CsvExporter();
        StringWriter outputWriter = new StringWriter();
        String moduleName = this.Entity.split("\\.")[0];
        String entityName = this.Entity.split("\\.")[1];

        csvExporter.entityToCsv(getContext(), outputWriter, moduleName, entityName,this.Delimiter);
        logger.info("Done exporting: " + outputWriter.toString());
        String result = outputWriter.toString();
        outputWriter.close();
        return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportCsvData";
	}

	// BEGIN EXTRA CODE
    private static ILogNode logger = Core.getLogger(CsvServicesImpl.LOG_NORE);

	// END EXTRA CODE
}
