// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvservices.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import csvservices.impl.CsvImporter;
import java.io.File;
import java.io.FileInputStream;
import java.io.StringWriter;
import java.util.Arrays;

public class ImportCsvResourceData extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String Entity;
	private java.lang.String CsvResourcePath;

	public ImportCsvResourceData(IContext context, java.lang.String Entity, java.lang.String CsvResourcePath)
	{
		super(context);
		this.Entity = Entity;
		this.CsvResourcePath = CsvResourcePath;
	}

	@Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info("executeAction: " + this.Entity + ", " + Arrays.toString(this.Entity.split("\\.")));

        CsvImporter csvImporter = new CsvImporter();
        String moduleName = this.Entity.split("\\.")[0];
        String entityName = this.Entity.split("\\.")[1];

        File myFile = new File(Core.getConfiguration().getResourcesPath() + File.separator + this.CsvResourcePath);
        try (FileInputStream fis = new FileInputStream(myFile);
             StringWriter outputWriter = new StringWriter()
        ) {
            csvImporter.csvToEntities(getContext(), outputWriter, moduleName, entityName, fis);
            logger.info("Done importing: " + outputWriter.toString());

        }
        return 0L;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ImportCsvResourceData";
	}

	// BEGIN EXTRA CODE
    private final ILogNode logger = Core.getLogger(this.getClass().getName());
	// END EXTRA CODE
}
