// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvservices.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import csvservices.impl.CsvImporter;
import csvservices.impl.CsvServicesImpl;
import java.io.InputStream;
import java.io.StringWriter;
import java.net.URL;
import java.util.Arrays;
import java.util.zip.GZIPInputStream;

public class ImportCsvUrlData extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String Entity;
	private java.lang.String CsvUrl;
	private java.lang.Long MaxRecords;
	private java.lang.Boolean HasHeader;
	private java.lang.String AlternativeHeader;

	public ImportCsvUrlData(IContext context, java.lang.String Entity, java.lang.String CsvUrl, java.lang.Long MaxRecords, java.lang.Boolean HasHeader, java.lang.String AlternativeHeader)
	{
		super(context);
		this.Entity = Entity;
		this.CsvUrl = CsvUrl;
		this.MaxRecords = MaxRecords;
		this.HasHeader = HasHeader;
		this.AlternativeHeader = AlternativeHeader;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info("executeAction: " + this.Entity + ", " + Arrays.toString(this.Entity.split("\\.")));

        CsvImporter csvImporter = new CsvImporter();
        String moduleName = this.Entity.split("\\.")[0];
        String entityName = this.Entity.split("\\.")[1];

        URL csvUrl = new URL(this.CsvUrl);
        InputStream is = null;
        try {
            if (this.CsvUrl.endsWith(".gz") || this.CsvUrl.endsWith(".gzip")) {
                is = new GZIPInputStream(csvUrl.openStream());
            } else {
                is = csvUrl.openStream();
            }
            try (StringWriter outputWriter = new StringWriter()) {
                csvImporter.csvToEntities(getContext(), outputWriter, moduleName, entityName, is, false, this.MaxRecords.intValue(), this.HasHeader, this.AlternativeHeader);
                logger.info("Done importing: " + outputWriter.toString());
            }
        } catch (Exception e) {
            logger.warn("csv import failed: " + e.getMessage());
            logger.error(e);
        } finally {
            if (is != null) {
                is.close();
            }
        }
        return 0L;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportCsvUrlData";
	}

	// BEGIN EXTRA CODE
    private static ILogNode logger = Core.getLogger(CsvServicesImpl.LOG_NORE);

	// END EXTRA CODE
}
