// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvservices.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import csvservices.impl.CsvImporter;
import csvservices.impl.CsvServicesImpl;

import java.io.ByteArrayInputStream;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;

public class ImportCsvData extends CustomJavaAction<java.lang.Long> {
    private java.lang.String Entity;
    private java.lang.String CsvData;
    private java.lang.Long MaxRecords;
    private java.lang.Boolean HasHeader;
    private java.lang.String AlternativeHeader;

    public ImportCsvData(IContext context, java.lang.String Entity, java.lang.String CsvData, java.lang.Long MaxRecords, java.lang.Boolean HasHeader, java.lang.String AlternativeHeader) {
        super(context);
        this.Entity = Entity;
        this.CsvData = CsvData;
        this.MaxRecords = MaxRecords;
        this.HasHeader = HasHeader;
        this.AlternativeHeader = AlternativeHeader;
    }

    @java.lang.Override
    public java.lang.Long executeAction() throws Exception {
        // BEGIN USER CODE
        logger.info("executeAction: " + this.Entity + ", " + Arrays.toString(this.Entity.split("\\.")));
        Long objectsCreated = 0l;
        CsvImporter csvImporter = new CsvImporter();
        StringWriter outputWriter = new StringWriter();
        String moduleName = this.Entity.split("\\.")[0];
        String entityName = this.Entity.split("\\.")[1];
        if (this.MaxRecords == null) {
            this.MaxRecords = new Long(-1);
        }
        objectsCreated = new Long(csvImporter.csvToEntities(getContext(), outputWriter, moduleName, entityName, new ByteArrayInputStream(this.CsvData.getBytes(StandardCharsets.UTF_8)), false, this.MaxRecords.intValue(), this.HasHeader, this.AlternativeHeader));
        logger.info("Done importing: " + outputWriter.toString());
        outputWriter.close();
        return objectsCreated;
        // END USER CODE
    }

    /**
     * Returns a string representation of this action
     */
    @java.lang.Override
    public java.lang.String toString() {
        return "ImportCsvData";
    }

    // BEGIN EXTRA CODE
    private static ILogNode logger = Core.getLogger(CsvServicesImpl.LOG_NORE);

    // END EXTRA CODE
}
