// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvservices.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import csvservices.impl.CsvImporter;
import csvservices.impl.CsvServicesImpl;
import java.io.File;
import java.io.FileInputStream;
import java.io.StringWriter;
import java.util.Arrays;

public class ImportCsvResourceData extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String Entity;
	private java.lang.String CsvResourcePath;
	private java.lang.Long MaxRecords;
	private java.lang.Boolean HasHeader;
	private java.lang.String AlternativeHeader;
	private java.lang.String Delimiter;

	public ImportCsvResourceData(IContext context, java.lang.String Entity, java.lang.String CsvResourcePath, java.lang.Long MaxRecords, java.lang.Boolean HasHeader, java.lang.String AlternativeHeader, java.lang.String Delimiter)
	{
		super(context);
		this.Entity = Entity;
		this.CsvResourcePath = CsvResourcePath;
		this.MaxRecords = MaxRecords;
		this.HasHeader = HasHeader;
		this.AlternativeHeader = AlternativeHeader;
		this.Delimiter = Delimiter;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info("executeAction - importCsvResourceData: " + this.Entity + ", " + Arrays.toString(this.Entity.split("\\.")));
        Long objectsCreated = 0L;
		int maxRecords = (this.MaxRecords == null) ? -1 : this.MaxRecords.intValue();
        CsvImporter csvImporter = new CsvImporter();
        String moduleName = this.Entity.split("\\.")[0];
        String entityName = this.Entity.split("\\.")[1];

        File myFile = new File(Core.getConfiguration().getResourcesPath() + File.separator + this.CsvResourcePath);
        try (FileInputStream fis = new FileInputStream(myFile);
             StringWriter outputWriter = new StringWriter()
        ) {
            objectsCreated = Long.valueOf(csvImporter.csvToEntities(getContext(), outputWriter, moduleName, entityName, fis, false, maxRecords, this.HasHeader, this.AlternativeHeader, this.Delimiter));
            logger.info("Done importing: " + outputWriter.toString());

        }
        return objectsCreated;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportCsvResourceData";
	}

	// BEGIN EXTRA CODE
    private static ILogNode logger = Core.getLogger(CsvServicesImpl.LOG_NORE);

	// END EXTRA CODE
}
