// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies;

public class AllTypes
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject allTypesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Tests.AllTypes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StringValue("StringValue"),
		LongValue("LongValue"),
		IntegerValue("IntegerValue"),
		HashedStringValue("HashedStringValue"),
		FloatValue("FloatValue"),
		EnumValue("EnumValue"),
		DecimalValue("DecimalValue"),
		CurrencyValue("CurrencyValue"),
		BooleanValue("BooleanValue"),
		BinaryValue("BinaryValue"),
		DateTimeValue("DateTimeValue"),
		String2Value("String2Value");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AllTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Tests.AllTypes"));
	}

	protected AllTypes(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject allTypesMendixObject)
	{
		if (allTypesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Tests.AllTypes", allTypesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Tests.AllTypes");

		this.allTypesMendixObject = allTypesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AllTypes.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static tests.proxies.AllTypes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return tests.proxies.AllTypes.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static tests.proxies.AllTypes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tests.proxies.AllTypes(context, mendixObject);
	}

	public static tests.proxies.AllTypes load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tests.proxies.AllTypes.initialize(context, mendixObject);
	}

	public static java.util.List<tests.proxies.AllTypes> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<tests.proxies.AllTypes> result = new java.util.ArrayList<tests.proxies.AllTypes>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Tests.AllTypes" + xpathConstraint))
			result.add(tests.proxies.AllTypes.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.String stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * @return value of LongValue
	 */
	public final java.lang.Long getLongValue()
	{
		return getLongValue(getContext());
	}

	/**
	 * @param context
	 * @return value of LongValue
	 */
	public final java.lang.Long getLongValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LongValue.toString());
	}

	/**
	 * Set value of LongValue
	 * @param longvalue
	 */
	public final void setLongValue(java.lang.Long longvalue)
	{
		setLongValue(getContext(), longvalue);
	}

	/**
	 * Set value of LongValue
	 * @param context
	 * @param longvalue
	 */
	public final void setLongValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longvalue)
	{
		getMendixObject().setValue(context, MemberNames.LongValue.toString(), longvalue);
	}

	/**
	 * @return value of IntegerValue
	 */
	public final java.lang.Integer getIntegerValue()
	{
		return getIntegerValue(getContext());
	}

	/**
	 * @param context
	 * @return value of IntegerValue
	 */
	public final java.lang.Integer getIntegerValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntegerValue.toString());
	}

	/**
	 * Set value of IntegerValue
	 * @param integervalue
	 */
	public final void setIntegerValue(java.lang.Integer integervalue)
	{
		setIntegerValue(getContext(), integervalue);
	}

	/**
	 * Set value of IntegerValue
	 * @param context
	 * @param integervalue
	 */
	public final void setIntegerValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integervalue)
	{
		getMendixObject().setValue(context, MemberNames.IntegerValue.toString(), integervalue);
	}

	/**
	 * Set value of HashedStringValue
	 * @param hashedstringvalue
	 */
	public final void setHashedStringValue(java.lang.String hashedstringvalue)
	{
		setHashedStringValue(getContext(), hashedstringvalue);
	}

	/**
	 * Set value of HashedStringValue
	 * @param context
	 * @param hashedstringvalue
	 */
	public final void setHashedStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hashedstringvalue)
	{
		getMendixObject().setValue(context, MemberNames.HashedStringValue.toString(), hashedstringvalue);
	}

	/**
	 * @return value of FloatValue
	 */
	public final java.lang.Double getFloatValue()
	{
		return getFloatValue(getContext());
	}

	/**
	 * @param context
	 * @return value of FloatValue
	 */
	public final java.lang.Double getFloatValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.FloatValue.toString());
	}

	/**
	 * Set value of FloatValue
	 * @param floatvalue
	 */
	public final void setFloatValue(java.lang.Double floatvalue)
	{
		setFloatValue(getContext(), floatvalue);
	}

	/**
	 * Set value of FloatValue
	 * @param context
	 * @param floatvalue
	 */
	public final void setFloatValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double floatvalue)
	{
		getMendixObject().setValue(context, MemberNames.FloatValue.toString(), floatvalue);
	}

	/**
	 * Set value of EnumValue
	 * @param enumvalue
	 */
	public final tests.proxies.YesNoEnum getEnumValue()
	{
		return getEnumValue(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumValue
	 */
	public final tests.proxies.YesNoEnum getEnumValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumValue.toString());
		if (obj == null)
			return null;

		return tests.proxies.YesNoEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumValue
	 * @param enumvalue
	 */
	public final void setEnumValue(tests.proxies.YesNoEnum enumvalue)
	{
		setEnumValue(getContext(), enumvalue);
	}

	/**
	 * Set value of EnumValue
	 * @param context
	 * @param enumvalue
	 */
	public final void setEnumValue(com.mendix.systemwideinterfaces.core.IContext context, tests.proxies.YesNoEnum enumvalue)
	{
		if (enumvalue != null)
			getMendixObject().setValue(context, MemberNames.EnumValue.toString(), enumvalue.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnumValue.toString(), null);
	}

	/**
	 * @return value of DecimalValue
	 */
	public final java.math.BigDecimal getDecimalValue()
	{
		return getDecimalValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DecimalValue
	 */
	public final java.math.BigDecimal getDecimalValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DecimalValue.toString());
	}

	/**
	 * Set value of DecimalValue
	 * @param decimalvalue
	 */
	public final void setDecimalValue(java.math.BigDecimal decimalvalue)
	{
		setDecimalValue(getContext(), decimalvalue);
	}

	/**
	 * Set value of DecimalValue
	 * @param context
	 * @param decimalvalue
	 */
	public final void setDecimalValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimalvalue)
	{
		getMendixObject().setValue(context, MemberNames.DecimalValue.toString(), decimalvalue);
	}

	/**
	 * @return value of CurrencyValue
	 */
	public final java.lang.Double getCurrencyValue()
	{
		return getCurrencyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrencyValue
	 */
	public final java.lang.Double getCurrencyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.CurrencyValue.toString());
	}

	/**
	 * Set value of CurrencyValue
	 * @param currencyvalue
	 */
	public final void setCurrencyValue(java.lang.Double currencyvalue)
	{
		setCurrencyValue(getContext(), currencyvalue);
	}

	/**
	 * Set value of CurrencyValue
	 * @param context
	 * @param currencyvalue
	 */
	public final void setCurrencyValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double currencyvalue)
	{
		getMendixObject().setValue(context, MemberNames.CurrencyValue.toString(), currencyvalue);
	}

	/**
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue()
	{
		return getBooleanValue(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanValue.toString());
	}

	/**
	 * Set value of BooleanValue
	 * @param booleanvalue
	 */
	public final void setBooleanValue(java.lang.Boolean booleanvalue)
	{
		setBooleanValue(getContext(), booleanvalue);
	}

	/**
	 * Set value of BooleanValue
	 * @param context
	 * @param booleanvalue
	 */
	public final void setBooleanValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanvalue)
	{
		getMendixObject().setValue(context, MemberNames.BooleanValue.toString(), booleanvalue);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getBinaryValue(com.mendix.systemwideinterfaces.core.IContext context, java.io.OutputStream outputStream)
	{
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.BinaryValue.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setBinaryValue(com.mendix.systemwideinterfaces.core.IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == com.mendix.systemwideinterfaces.core.IMendixObject.ObjectState.INSTANTIATED)
			try { commit(); } catch (com.mendix.core.CoreException ex) { }
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.BinaryValue.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue()
	{
		return getDateTimeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTimeValue.toString());
	}

	/**
	 * Set value of DateTimeValue
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(java.util.Date datetimevalue)
	{
		setDateTimeValue(getContext(), datetimevalue);
	}

	/**
	 * Set value of DateTimeValue
	 * @param context
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimevalue)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeValue.toString(), datetimevalue);
	}

	/**
	 * @return value of String2Value
	 */
	public final java.lang.String getString2Value()
	{
		return getString2Value(getContext());
	}

	/**
	 * @param context
	 * @return value of String2Value
	 */
	public final java.lang.String getString2Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.String2Value.toString());
	}

	/**
	 * Set value of String2Value
	 * @param string2value
	 */
	public final void setString2Value(java.lang.String string2value)
	{
		setString2Value(getContext(), string2value);
	}

	/**
	 * Set value of String2Value
	 * @param context
	 * @param string2value
	 */
	public final void setString2Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String string2value)
	{
		getMendixObject().setValue(context, MemberNames.String2Value.toString(), string2value);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return allTypesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tests.proxies.AllTypes that = (tests.proxies.AllTypes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Tests.AllTypes";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
