// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies;

public enum YesNoEnum
{
	Yes(new String[][] { new String[] { "en_US", "Yes" } }),
	No(new String[][] { new String[] { "en_US", "No" } });

	private java.util.Map<String,String> captions;

	private YesNoEnum(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
