// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package csvservices.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the CsvServices module

	public static String getCSV_SERVICES_VERSION()
	{
		return (String)Core.getConfiguration().getConstantValue("CsvServices.CSV_SERVICES_VERSION");
	}
}