// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package orders.proxies;

public class Customers
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Orders.Customers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CustomerId("CustomerId"),
		Firstname("Firstname"),
		Lastname("Lastname"),
		DateOfBirth("DateOfBirth"),
		Billing_Address("Orders.Billing_Address"),
		Delivery_Address("Orders.Delivery_Address");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Customers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customersMendixObject)
	{
		if (customersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, customersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.customersMendixObject = customersMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Customers.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static orders.proxies.Customers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return orders.proxies.Customers.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static orders.proxies.Customers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new orders.proxies.Customers(context, mendixObject);
	}

	public static orders.proxies.Customers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return orders.proxies.Customers.initialize(context, mendixObject);
	}

	public static java.util.List<orders.proxies.Customers> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> orders.proxies.Customers.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CustomerId
	 */
	public final java.lang.Long getCustomerId()
	{
		return getCustomerId(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerId
	 */
	public final java.lang.Long getCustomerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CustomerId.toString());
	}

	/**
	 * Set value of CustomerId
	 * @param customerid
	 */
	public final void setCustomerId(java.lang.Long customerid)
	{
		setCustomerId(getContext(), customerid);
	}

	/**
	 * Set value of CustomerId
	 * @param context
	 * @param customerid
	 */
	public final void setCustomerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long customerid)
	{
		getMendixObject().setValue(context, MemberNames.CustomerId.toString(), customerid);
	}

	/**
	 * @return value of Firstname
	 */
	public final java.lang.String getFirstname()
	{
		return getFirstname(getContext());
	}

	/**
	 * @param context
	 * @return value of Firstname
	 */
	public final java.lang.String getFirstname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Firstname.toString());
	}

	/**
	 * Set value of Firstname
	 * @param firstname
	 */
	public final void setFirstname(java.lang.String firstname)
	{
		setFirstname(getContext(), firstname);
	}

	/**
	 * Set value of Firstname
	 * @param context
	 * @param firstname
	 */
	public final void setFirstname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.Firstname.toString(), firstname);
	}

	/**
	 * @return value of Lastname
	 */
	public final java.lang.String getLastname()
	{
		return getLastname(getContext());
	}

	/**
	 * @param context
	 * @return value of Lastname
	 */
	public final java.lang.String getLastname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Lastname.toString());
	}

	/**
	 * Set value of Lastname
	 * @param lastname
	 */
	public final void setLastname(java.lang.String lastname)
	{
		setLastname(getContext(), lastname);
	}

	/**
	 * Set value of Lastname
	 * @param context
	 * @param lastname
	 */
	public final void setLastname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.Lastname.toString(), lastname);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Billing_Address
	 */
	public final orders.proxies.Address getBilling_Address() throws com.mendix.core.CoreException
	{
		return getBilling_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of Billing_Address
	 * @throws com.mendix.core.CoreException
	 */
	public final orders.proxies.Address getBilling_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		orders.proxies.Address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Billing_Address.toString());
		if (identifier != null) {
			result = orders.proxies.Address.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Billing_Address
	 * @param billing_address
	 */
	public final void setBilling_Address(orders.proxies.Address billing_address)
	{
		setBilling_Address(getContext(), billing_address);
	}

	/**
	 * Set value of Billing_Address
	 * @param context
	 * @param billing_address
	 */
	public final void setBilling_Address(com.mendix.systemwideinterfaces.core.IContext context, orders.proxies.Address billing_address)
	{
		if (billing_address == null) {
			getMendixObject().setValue(context, MemberNames.Billing_Address.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Billing_Address.toString(), billing_address.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Delivery_Address
	 */
	public final orders.proxies.Address getDelivery_Address() throws com.mendix.core.CoreException
	{
		return getDelivery_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of Delivery_Address
	 * @throws com.mendix.core.CoreException
	 */
	public final orders.proxies.Address getDelivery_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		orders.proxies.Address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Delivery_Address.toString());
		if (identifier != null) {
			result = orders.proxies.Address.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Delivery_Address
	 * @param delivery_address
	 */
	public final void setDelivery_Address(orders.proxies.Address delivery_address)
	{
		setDelivery_Address(getContext(), delivery_address);
	}

	/**
	 * Set value of Delivery_Address
	 * @param context
	 * @param delivery_address
	 */
	public final void setDelivery_Address(com.mendix.systemwideinterfaces.core.IContext context, orders.proxies.Address delivery_address)
	{
		if (delivery_address == null) {
			getMendixObject().setValue(context, MemberNames.Delivery_Address.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Delivery_Address.toString(), delivery_address.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customersMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final orders.proxies.Customers that = (orders.proxies.Customers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
