// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package orders.proxies;

public class Orders
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ordersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Orders.Orders";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		OrderDate("OrderDate"),
		Order_Customer("Orders.Order_Customer");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Orders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Orders.Orders"));
	}

	protected Orders(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ordersMendixObject)
	{
		if (ordersMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Orders.Orders", ordersMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Orders.Orders");

		this.ordersMendixObject = ordersMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Orders.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static orders.proxies.Orders initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return orders.proxies.Orders.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static orders.proxies.Orders initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new orders.proxies.Orders(context, mendixObject);
	}

	public static orders.proxies.Orders load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return orders.proxies.Orders.initialize(context, mendixObject);
	}

	public static java.util.List<orders.proxies.Orders> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<orders.proxies.Orders> result = new java.util.ArrayList<orders.proxies.Orders>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Orders.Orders" + xpathConstraint))
			result.add(orders.proxies.Orders.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OrderNumber
	 */
	public final java.lang.Long getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final java.lang.Long getOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(java.lang.Long ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of Order_Customer
	 */
	public final orders.proxies.Customers getOrder_Customer() throws com.mendix.core.CoreException
	{
		return getOrder_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Customer
	 */
	public final orders.proxies.Customers getOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		orders.proxies.Customers result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Customer.toString());
		if (identifier != null)
			result = orders.proxies.Customers.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Order_Customer
	 * @param order_customer
	 */
	public final void setOrder_Customer(orders.proxies.Customers order_customer)
	{
		setOrder_Customer(getContext(), order_customer);
	}

	/**
	 * Set value of Order_Customer
	 * @param context
	 * @param order_customer
	 */
	public final void setOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context, orders.proxies.Customers order_customer)
	{
		if (order_customer == null)
			getMendixObject().setValue(context, MemberNames.Order_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Order_Customer.toString(), order_customer.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ordersMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final orders.proxies.Orders that = (orders.proxies.Orders) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Orders.Orders";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
