// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package orders.proxies;

public class OrderLines
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderLinesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Orders.OrderLines";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LineId("LineId"),
		LineNo("LineNo"),
		Quantity("Quantity"),
		Line_Product("Orders.Line_Product"),
		Order_Lines("Orders.Order_Lines");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderLines(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OrderLines(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderLinesMendixObject)
	{
		if (orderLinesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, orderLinesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderLinesMendixObject = orderLinesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OrderLines.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static orders.proxies.OrderLines initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return orders.proxies.OrderLines.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static orders.proxies.OrderLines initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new orders.proxies.OrderLines(context, mendixObject);
	}

	public static orders.proxies.OrderLines load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return orders.proxies.OrderLines.initialize(context, mendixObject);
	}

	public static java.util.List<orders.proxies.OrderLines> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> orders.proxies.OrderLines.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LineId
	 */
	public final java.lang.Long getLineId()
	{
		return getLineId(getContext());
	}

	/**
	 * @param context
	 * @return value of LineId
	 */
	public final java.lang.Long getLineId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LineId.toString());
	}

	/**
	 * Set value of LineId
	 * @param lineid
	 */
	public final void setLineId(java.lang.Long lineid)
	{
		setLineId(getContext(), lineid);
	}

	/**
	 * Set value of LineId
	 * @param context
	 * @param lineid
	 */
	public final void setLineId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long lineid)
	{
		getMendixObject().setValue(context, MemberNames.LineId.toString(), lineid);
	}

	/**
	 * @return value of LineNo
	 */
	public final java.lang.Long getLineNo()
	{
		return getLineNo(getContext());
	}

	/**
	 * @param context
	 * @return value of LineNo
	 */
	public final java.lang.Long getLineNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LineNo.toString());
	}

	/**
	 * Set value of LineNo
	 * @param lineno
	 */
	public final void setLineNo(java.lang.Long lineno)
	{
		setLineNo(getContext(), lineno);
	}

	/**
	 * Set value of LineNo
	 * @param context
	 * @param lineno
	 */
	public final void setLineNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long lineno)
	{
		getMendixObject().setValue(context, MemberNames.LineNo.toString(), lineno);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Long getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Long getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Long quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Line_Product
	 */
	public final orders.proxies.Products getLine_Product() throws com.mendix.core.CoreException
	{
		return getLine_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of Line_Product
	 * @throws com.mendix.core.CoreException
	 */
	public final orders.proxies.Products getLine_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		orders.proxies.Products result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Line_Product.toString());
		if (identifier != null) {
			result = orders.proxies.Products.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Line_Product
	 * @param line_product
	 */
	public final void setLine_Product(orders.proxies.Products line_product)
	{
		setLine_Product(getContext(), line_product);
	}

	/**
	 * Set value of Line_Product
	 * @param context
	 * @param line_product
	 */
	public final void setLine_Product(com.mendix.systemwideinterfaces.core.IContext context, orders.proxies.Products line_product)
	{
		if (line_product == null) {
			getMendixObject().setValue(context, MemberNames.Line_Product.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Line_Product.toString(), line_product.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Lines
	 */
	public final orders.proxies.Orders getOrder_Lines() throws com.mendix.core.CoreException
	{
		return getOrder_Lines(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Lines
	 * @throws com.mendix.core.CoreException
	 */
	public final orders.proxies.Orders getOrder_Lines(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		orders.proxies.Orders result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Lines.toString());
		if (identifier != null) {
			result = orders.proxies.Orders.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_Lines
	 * @param order_lines
	 */
	public final void setOrder_Lines(orders.proxies.Orders order_lines)
	{
		setOrder_Lines(getContext(), order_lines);
	}

	/**
	 * Set value of Order_Lines
	 * @param context
	 * @param order_lines
	 */
	public final void setOrder_Lines(com.mendix.systemwideinterfaces.core.IContext context, orders.proxies.Orders order_lines)
	{
		if (order_lines == null) {
			getMendixObject().setValue(context, MemberNames.Order_Lines.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_Lines.toString(), order_lines.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderLinesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final orders.proxies.OrderLines that = (orders.proxies.OrderLines) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
