// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imdbtests.proxies;

/**
 * Alternative known as
 */
public class Akas
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject akasMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImdbTests.Akas";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TitleId("TitleId"),
		Ordering("Ordering"),
		Title("Title"),
		Region("Region"),
		Language("Language"),
		Types("Types"),
		Attributes("Attributes"),
		IsOriginalTitle("IsOriginalTitle"),
		Akas_Title("ImdbTests.Akas_Title");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Akas(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Akas(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject akasMendixObject)
	{
		if (akasMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, akasMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.akasMendixObject = akasMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Akas.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imdbtests.proxies.Akas initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imdbtests.proxies.Akas.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static imdbtests.proxies.Akas initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imdbtests.proxies.Akas(context, mendixObject);
	}

	public static imdbtests.proxies.Akas load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imdbtests.proxies.Akas.initialize(context, mendixObject);
	}

	public static java.util.List<imdbtests.proxies.Akas> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> imdbtests.proxies.Akas.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TitleId
	 */
	public final java.lang.String getTitleId()
	{
		return getTitleId(getContext());
	}

	/**
	 * @param context
	 * @return value of TitleId
	 */
	public final java.lang.String getTitleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TitleId.toString());
	}

	/**
	 * Set value of TitleId
	 * @param titleid
	 */
	public final void setTitleId(java.lang.String titleid)
	{
		setTitleId(getContext(), titleid);
	}

	/**
	 * Set value of TitleId
	 * @param context
	 * @param titleid
	 */
	public final void setTitleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titleid)
	{
		getMendixObject().setValue(context, MemberNames.TitleId.toString(), titleid);
	}

	/**
	 * @return value of Ordering
	 */
	public final java.lang.Long getOrdering()
	{
		return getOrdering(getContext());
	}

	/**
	 * @param context
	 * @return value of Ordering
	 */
	public final java.lang.Long getOrdering(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Ordering.toString());
	}

	/**
	 * Set value of Ordering
	 * @param ordering
	 */
	public final void setOrdering(java.lang.Long ordering)
	{
		setOrdering(getContext(), ordering);
	}

	/**
	 * Set value of Ordering
	 * @param context
	 * @param ordering
	 */
	public final void setOrdering(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ordering)
	{
		getMendixObject().setValue(context, MemberNames.Ordering.toString(), ordering);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of Language
	 */
	public final java.lang.String getLanguage()
	{
		return getLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of Language
	 */
	public final java.lang.String getLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Language.toString());
	}

	/**
	 * Set value of Language
	 * @param language
	 */
	public final void setLanguage(java.lang.String language)
	{
		setLanguage(getContext(), language);
	}

	/**
	 * Set value of Language
	 * @param context
	 * @param language
	 */
	public final void setLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String language)
	{
		getMendixObject().setValue(context, MemberNames.Language.toString(), language);
	}

	/**
	 * @return value of Types
	 */
	public final java.lang.String getTypes()
	{
		return getTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of Types
	 */
	public final java.lang.String getTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Types.toString());
	}

	/**
	 * Set value of Types
	 * @param types
	 */
	public final void setTypes(java.lang.String types)
	{
		setTypes(getContext(), types);
	}

	/**
	 * Set value of Types
	 * @param context
	 * @param types
	 */
	public final void setTypes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String types)
	{
		getMendixObject().setValue(context, MemberNames.Types.toString(), types);
	}

	/**
	 * @return value of Attributes
	 */
	public final java.lang.String getAttributes()
	{
		return getAttributes(getContext());
	}

	/**
	 * @param context
	 * @return value of Attributes
	 */
	public final java.lang.String getAttributes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attributes.toString());
	}

	/**
	 * Set value of Attributes
	 * @param attributes
	 */
	public final void setAttributes(java.lang.String attributes)
	{
		setAttributes(getContext(), attributes);
	}

	/**
	 * Set value of Attributes
	 * @param context
	 * @param attributes
	 */
	public final void setAttributes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributes)
	{
		getMendixObject().setValue(context, MemberNames.Attributes.toString(), attributes);
	}

	/**
	 * @return value of IsOriginalTitle
	 */
	public final java.lang.Boolean getIsOriginalTitle()
	{
		return getIsOriginalTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of IsOriginalTitle
	 */
	public final java.lang.Boolean getIsOriginalTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsOriginalTitle.toString());
	}

	/**
	 * Set value of IsOriginalTitle
	 * @param isoriginaltitle
	 */
	public final void setIsOriginalTitle(java.lang.Boolean isoriginaltitle)
	{
		setIsOriginalTitle(getContext(), isoriginaltitle);
	}

	/**
	 * Set value of IsOriginalTitle
	 * @param context
	 * @param isoriginaltitle
	 */
	public final void setIsOriginalTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isoriginaltitle)
	{
		getMendixObject().setValue(context, MemberNames.IsOriginalTitle.toString(), isoriginaltitle);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Akas_Title
	 */
	public final imdbtests.proxies.Title getAkas_Title() throws com.mendix.core.CoreException
	{
		return getAkas_Title(getContext());
	}

	/**
	 * @param context
	 * @return value of Akas_Title
	 * @throws com.mendix.core.CoreException
	 */
	public final imdbtests.proxies.Title getAkas_Title(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imdbtests.proxies.Title result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Akas_Title.toString());
		if (identifier != null) {
			result = imdbtests.proxies.Title.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Akas_Title
	 * @param akas_title
	 */
	public final void setAkas_Title(imdbtests.proxies.Title akas_title)
	{
		setAkas_Title(getContext(), akas_title);
	}

	/**
	 * Set value of Akas_Title
	 * @param context
	 * @param akas_title
	 */
	public final void setAkas_Title(com.mendix.systemwideinterfaces.core.IContext context, imdbtests.proxies.Title akas_title)
	{
		if (akas_title == null) {
			getMendixObject().setValue(context, MemberNames.Akas_Title.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Akas_Title.toString(), akas_title.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return akasMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imdbtests.proxies.Akas that = (imdbtests.proxies.Akas) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
