// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imdbtests.proxies;

public class Crew
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject crewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImdbTests.Crew";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TitleId("TitleId"),
		Directors("Directors"),
		Writers("Writers"),
		Crew_Title("ImdbTests.Crew_Title"),
		Directors_Names("ImdbTests.Directors_Names"),
		Writers_Names("ImdbTests.Writers_Names");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Crew(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Crew(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject crewMendixObject)
	{
		if (crewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, crewMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.crewMendixObject = crewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Crew.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imdbtests.proxies.Crew initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imdbtests.proxies.Crew.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static imdbtests.proxies.Crew initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imdbtests.proxies.Crew(context, mendixObject);
	}

	public static imdbtests.proxies.Crew load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imdbtests.proxies.Crew.initialize(context, mendixObject);
	}

	public static java.util.List<imdbtests.proxies.Crew> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> imdbtests.proxies.Crew.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TitleId
	 */
	public final java.lang.String getTitleId()
	{
		return getTitleId(getContext());
	}

	/**
	 * @param context
	 * @return value of TitleId
	 */
	public final java.lang.String getTitleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TitleId.toString());
	}

	/**
	 * Set value of TitleId
	 * @param titleid
	 */
	public final void setTitleId(java.lang.String titleid)
	{
		setTitleId(getContext(), titleid);
	}

	/**
	 * Set value of TitleId
	 * @param context
	 * @param titleid
	 */
	public final void setTitleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titleid)
	{
		getMendixObject().setValue(context, MemberNames.TitleId.toString(), titleid);
	}

	/**
	 * @return value of Directors
	 */
	public final java.lang.String getDirectors()
	{
		return getDirectors(getContext());
	}

	/**
	 * @param context
	 * @return value of Directors
	 */
	public final java.lang.String getDirectors(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Directors.toString());
	}

	/**
	 * Set value of Directors
	 * @param directors
	 */
	public final void setDirectors(java.lang.String directors)
	{
		setDirectors(getContext(), directors);
	}

	/**
	 * Set value of Directors
	 * @param context
	 * @param directors
	 */
	public final void setDirectors(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String directors)
	{
		getMendixObject().setValue(context, MemberNames.Directors.toString(), directors);
	}

	/**
	 * @return value of Writers
	 */
	public final java.lang.String getWriters()
	{
		return getWriters(getContext());
	}

	/**
	 * @param context
	 * @return value of Writers
	 */
	public final java.lang.String getWriters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Writers.toString());
	}

	/**
	 * Set value of Writers
	 * @param writers
	 */
	public final void setWriters(java.lang.String writers)
	{
		setWriters(getContext(), writers);
	}

	/**
	 * Set value of Writers
	 * @param context
	 * @param writers
	 */
	public final void setWriters(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String writers)
	{
		getMendixObject().setValue(context, MemberNames.Writers.toString(), writers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Crew_Title
	 */
	public final imdbtests.proxies.Title getCrew_Title() throws com.mendix.core.CoreException
	{
		return getCrew_Title(getContext());
	}

	/**
	 * @param context
	 * @return value of Crew_Title
	 * @throws com.mendix.core.CoreException
	 */
	public final imdbtests.proxies.Title getCrew_Title(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imdbtests.proxies.Title result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Crew_Title.toString());
		if (identifier != null) {
			result = imdbtests.proxies.Title.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Crew_Title
	 * @param crew_title
	 */
	public final void setCrew_Title(imdbtests.proxies.Title crew_title)
	{
		setCrew_Title(getContext(), crew_title);
	}

	/**
	 * Set value of Crew_Title
	 * @param context
	 * @param crew_title
	 */
	public final void setCrew_Title(com.mendix.systemwideinterfaces.core.IContext context, imdbtests.proxies.Title crew_title)
	{
		if (crew_title == null) {
			getMendixObject().setValue(context, MemberNames.Crew_Title.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Crew_Title.toString(), crew_title.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Directors_Names
	 */
	public final imdbtests.proxies.NameBasics getDirectors_Names() throws com.mendix.core.CoreException
	{
		return getDirectors_Names(getContext());
	}

	/**
	 * @param context
	 * @return value of Directors_Names
	 * @throws com.mendix.core.CoreException
	 */
	public final imdbtests.proxies.NameBasics getDirectors_Names(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imdbtests.proxies.NameBasics result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Directors_Names.toString());
		if (identifier != null) {
			result = imdbtests.proxies.NameBasics.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Directors_Names
	 * @param directors_names
	 */
	public final void setDirectors_Names(imdbtests.proxies.NameBasics directors_names)
	{
		setDirectors_Names(getContext(), directors_names);
	}

	/**
	 * Set value of Directors_Names
	 * @param context
	 * @param directors_names
	 */
	public final void setDirectors_Names(com.mendix.systemwideinterfaces.core.IContext context, imdbtests.proxies.NameBasics directors_names)
	{
		if (directors_names == null) {
			getMendixObject().setValue(context, MemberNames.Directors_Names.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Directors_Names.toString(), directors_names.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Writers_Names
	 */
	public final imdbtests.proxies.NameBasics getWriters_Names() throws com.mendix.core.CoreException
	{
		return getWriters_Names(getContext());
	}

	/**
	 * @param context
	 * @return value of Writers_Names
	 * @throws com.mendix.core.CoreException
	 */
	public final imdbtests.proxies.NameBasics getWriters_Names(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imdbtests.proxies.NameBasics result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Writers_Names.toString());
		if (identifier != null) {
			result = imdbtests.proxies.NameBasics.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Writers_Names
	 * @param writers_names
	 */
	public final void setWriters_Names(imdbtests.proxies.NameBasics writers_names)
	{
		setWriters_Names(getContext(), writers_names);
	}

	/**
	 * Set value of Writers_Names
	 * @param context
	 * @param writers_names
	 */
	public final void setWriters_Names(com.mendix.systemwideinterfaces.core.IContext context, imdbtests.proxies.NameBasics writers_names)
	{
		if (writers_names == null) {
			getMendixObject().setValue(context, MemberNames.Writers_Names.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Writers_Names.toString(), writers_names.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return crewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imdbtests.proxies.Crew that = (imdbtests.proxies.Crew) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
