// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imdbtests.proxies;

public class Episodes
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject episodesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImdbTests.Episodes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EpisodeId("EpisodeId"),
		ParentTitleId("ParentTitleId"),
		SeasonNumber("SeasonNumber"),
		EpisodeNumber("EpisodeNumber"),
		Episodes_Title("ImdbTests.Episodes_Title");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Episodes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ImdbTests.Episodes"));
	}

	protected Episodes(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject episodesMendixObject)
	{
		if (episodesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ImdbTests.Episodes", episodesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ImdbTests.Episodes");

		this.episodesMendixObject = episodesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Episodes.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imdbtests.proxies.Episodes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imdbtests.proxies.Episodes.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static imdbtests.proxies.Episodes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imdbtests.proxies.Episodes(context, mendixObject);
	}

	public static imdbtests.proxies.Episodes load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imdbtests.proxies.Episodes.initialize(context, mendixObject);
	}

	public static java.util.List<imdbtests.proxies.Episodes> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<imdbtests.proxies.Episodes> result = new java.util.ArrayList<imdbtests.proxies.Episodes>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ImdbTests.Episodes" + xpathConstraint))
			result.add(imdbtests.proxies.Episodes.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EpisodeId
	 */
	public final java.lang.String getEpisodeId()
	{
		return getEpisodeId(getContext());
	}

	/**
	 * @param context
	 * @return value of EpisodeId
	 */
	public final java.lang.String getEpisodeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EpisodeId.toString());
	}

	/**
	 * Set value of EpisodeId
	 * @param episodeid
	 */
	public final void setEpisodeId(java.lang.String episodeid)
	{
		setEpisodeId(getContext(), episodeid);
	}

	/**
	 * Set value of EpisodeId
	 * @param context
	 * @param episodeid
	 */
	public final void setEpisodeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String episodeid)
	{
		getMendixObject().setValue(context, MemberNames.EpisodeId.toString(), episodeid);
	}

	/**
	 * @return value of ParentTitleId
	 */
	public final java.lang.String getParentTitleId()
	{
		return getParentTitleId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentTitleId
	 */
	public final java.lang.String getParentTitleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentTitleId.toString());
	}

	/**
	 * Set value of ParentTitleId
	 * @param parenttitleid
	 */
	public final void setParentTitleId(java.lang.String parenttitleid)
	{
		setParentTitleId(getContext(), parenttitleid);
	}

	/**
	 * Set value of ParentTitleId
	 * @param context
	 * @param parenttitleid
	 */
	public final void setParentTitleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parenttitleid)
	{
		getMendixObject().setValue(context, MemberNames.ParentTitleId.toString(), parenttitleid);
	}

	/**
	 * @return value of SeasonNumber
	 */
	public final java.lang.Integer getSeasonNumber()
	{
		return getSeasonNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of SeasonNumber
	 */
	public final java.lang.Integer getSeasonNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SeasonNumber.toString());
	}

	/**
	 * Set value of SeasonNumber
	 * @param seasonnumber
	 */
	public final void setSeasonNumber(java.lang.Integer seasonnumber)
	{
		setSeasonNumber(getContext(), seasonnumber);
	}

	/**
	 * Set value of SeasonNumber
	 * @param context
	 * @param seasonnumber
	 */
	public final void setSeasonNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seasonnumber)
	{
		getMendixObject().setValue(context, MemberNames.SeasonNumber.toString(), seasonnumber);
	}

	/**
	 * @return value of EpisodeNumber
	 */
	public final java.lang.Integer getEpisodeNumber()
	{
		return getEpisodeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EpisodeNumber
	 */
	public final java.lang.Integer getEpisodeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EpisodeNumber.toString());
	}

	/**
	 * Set value of EpisodeNumber
	 * @param episodenumber
	 */
	public final void setEpisodeNumber(java.lang.Integer episodenumber)
	{
		setEpisodeNumber(getContext(), episodenumber);
	}

	/**
	 * Set value of EpisodeNumber
	 * @param context
	 * @param episodenumber
	 */
	public final void setEpisodeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer episodenumber)
	{
		getMendixObject().setValue(context, MemberNames.EpisodeNumber.toString(), episodenumber);
	}

	/**
	 * @return value of Episodes_Title
	 */
	public final imdbtests.proxies.Title getEpisodes_Title() throws com.mendix.core.CoreException
	{
		return getEpisodes_Title(getContext());
	}

	/**
	 * @param context
	 * @return value of Episodes_Title
	 */
	public final imdbtests.proxies.Title getEpisodes_Title(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imdbtests.proxies.Title result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Episodes_Title.toString());
		if (identifier != null)
			result = imdbtests.proxies.Title.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Episodes_Title
	 * @param episodes_title
	 */
	public final void setEpisodes_Title(imdbtests.proxies.Title episodes_title)
	{
		setEpisodes_Title(getContext(), episodes_title);
	}

	/**
	 * Set value of Episodes_Title
	 * @param context
	 * @param episodes_title
	 */
	public final void setEpisodes_Title(com.mendix.systemwideinterfaces.core.IContext context, imdbtests.proxies.Title episodes_title)
	{
		if (episodes_title == null)
			getMendixObject().setValue(context, MemberNames.Episodes_Title.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Episodes_Title.toString(), episodes_title.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return episodesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imdbtests.proxies.Episodes that = (imdbtests.proxies.Episodes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ImdbTests.Episodes";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
