// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imdbtests.proxies;

public class Title
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject titleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImdbTests.Title";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TitleId("TitleId"),
		TitleType("TitleType"),
		PrimaryTitle("PrimaryTitle"),
		OriginalTitle("OriginalTitle"),
		IsAdult("IsAdult"),
		StartYear("StartYear"),
		EndYear("EndYear"),
		RuntimeMinutes("RuntimeMinutes"),
		Genres("Genres"),
		KnownForTitles("ImdbTests.KnownForTitles");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Title(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Title(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject titleMendixObject)
	{
		if (titleMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, titleMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.titleMendixObject = titleMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Title.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imdbtests.proxies.Title initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imdbtests.proxies.Title.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static imdbtests.proxies.Title initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imdbtests.proxies.Title(context, mendixObject);
	}

	public static imdbtests.proxies.Title load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imdbtests.proxies.Title.initialize(context, mendixObject);
	}

	public static java.util.List<imdbtests.proxies.Title> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> imdbtests.proxies.Title.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TitleId
	 */
	public final java.lang.String getTitleId()
	{
		return getTitleId(getContext());
	}

	/**
	 * @param context
	 * @return value of TitleId
	 */
	public final java.lang.String getTitleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TitleId.toString());
	}

	/**
	 * Set value of TitleId
	 * @param titleid
	 */
	public final void setTitleId(java.lang.String titleid)
	{
		setTitleId(getContext(), titleid);
	}

	/**
	 * Set value of TitleId
	 * @param context
	 * @param titleid
	 */
	public final void setTitleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titleid)
	{
		getMendixObject().setValue(context, MemberNames.TitleId.toString(), titleid);
	}

	/**
	 * @return value of TitleType
	 */
	public final java.lang.String getTitleType()
	{
		return getTitleType(getContext());
	}

	/**
	 * @param context
	 * @return value of TitleType
	 */
	public final java.lang.String getTitleType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TitleType.toString());
	}

	/**
	 * Set value of TitleType
	 * @param titletype
	 */
	public final void setTitleType(java.lang.String titletype)
	{
		setTitleType(getContext(), titletype);
	}

	/**
	 * Set value of TitleType
	 * @param context
	 * @param titletype
	 */
	public final void setTitleType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titletype)
	{
		getMendixObject().setValue(context, MemberNames.TitleType.toString(), titletype);
	}

	/**
	 * @return value of PrimaryTitle
	 */
	public final java.lang.String getPrimaryTitle()
	{
		return getPrimaryTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of PrimaryTitle
	 */
	public final java.lang.String getPrimaryTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PrimaryTitle.toString());
	}

	/**
	 * Set value of PrimaryTitle
	 * @param primarytitle
	 */
	public final void setPrimaryTitle(java.lang.String primarytitle)
	{
		setPrimaryTitle(getContext(), primarytitle);
	}

	/**
	 * Set value of PrimaryTitle
	 * @param context
	 * @param primarytitle
	 */
	public final void setPrimaryTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String primarytitle)
	{
		getMendixObject().setValue(context, MemberNames.PrimaryTitle.toString(), primarytitle);
	}

	/**
	 * @return value of OriginalTitle
	 */
	public final java.lang.String getOriginalTitle()
	{
		return getOriginalTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginalTitle
	 */
	public final java.lang.String getOriginalTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OriginalTitle.toString());
	}

	/**
	 * Set value of OriginalTitle
	 * @param originaltitle
	 */
	public final void setOriginalTitle(java.lang.String originaltitle)
	{
		setOriginalTitle(getContext(), originaltitle);
	}

	/**
	 * Set value of OriginalTitle
	 * @param context
	 * @param originaltitle
	 */
	public final void setOriginalTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String originaltitle)
	{
		getMendixObject().setValue(context, MemberNames.OriginalTitle.toString(), originaltitle);
	}

	/**
	 * @return value of IsAdult
	 */
	public final java.lang.Boolean getIsAdult()
	{
		return getIsAdult(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAdult
	 */
	public final java.lang.Boolean getIsAdult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAdult.toString());
	}

	/**
	 * Set value of IsAdult
	 * @param isadult
	 */
	public final void setIsAdult(java.lang.Boolean isadult)
	{
		setIsAdult(getContext(), isadult);
	}

	/**
	 * Set value of IsAdult
	 * @param context
	 * @param isadult
	 */
	public final void setIsAdult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isadult)
	{
		getMendixObject().setValue(context, MemberNames.IsAdult.toString(), isadult);
	}

	/**
	 * @return value of StartYear
	 */
	public final java.lang.Integer getStartYear()
	{
		return getStartYear(getContext());
	}

	/**
	 * @param context
	 * @return value of StartYear
	 */
	public final java.lang.Integer getStartYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StartYear.toString());
	}

	/**
	 * Set value of StartYear
	 * @param startyear
	 */
	public final void setStartYear(java.lang.Integer startyear)
	{
		setStartYear(getContext(), startyear);
	}

	/**
	 * Set value of StartYear
	 * @param context
	 * @param startyear
	 */
	public final void setStartYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer startyear)
	{
		getMendixObject().setValue(context, MemberNames.StartYear.toString(), startyear);
	}

	/**
	 * @return value of EndYear
	 */
	public final java.lang.Integer getEndYear()
	{
		return getEndYear(getContext());
	}

	/**
	 * @param context
	 * @return value of EndYear
	 */
	public final java.lang.Integer getEndYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EndYear.toString());
	}

	/**
	 * Set value of EndYear
	 * @param endyear
	 */
	public final void setEndYear(java.lang.Integer endyear)
	{
		setEndYear(getContext(), endyear);
	}

	/**
	 * Set value of EndYear
	 * @param context
	 * @param endyear
	 */
	public final void setEndYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer endyear)
	{
		getMendixObject().setValue(context, MemberNames.EndYear.toString(), endyear);
	}

	/**
	 * @return value of RuntimeMinutes
	 */
	public final java.lang.Integer getRuntimeMinutes()
	{
		return getRuntimeMinutes(getContext());
	}

	/**
	 * @param context
	 * @return value of RuntimeMinutes
	 */
	public final java.lang.Integer getRuntimeMinutes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RuntimeMinutes.toString());
	}

	/**
	 * Set value of RuntimeMinutes
	 * @param runtimeminutes
	 */
	public final void setRuntimeMinutes(java.lang.Integer runtimeminutes)
	{
		setRuntimeMinutes(getContext(), runtimeminutes);
	}

	/**
	 * Set value of RuntimeMinutes
	 * @param context
	 * @param runtimeminutes
	 */
	public final void setRuntimeMinutes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer runtimeminutes)
	{
		getMendixObject().setValue(context, MemberNames.RuntimeMinutes.toString(), runtimeminutes);
	}

	/**
	 * @return value of Genres
	 */
	public final java.lang.String getGenres()
	{
		return getGenres(getContext());
	}

	/**
	 * @param context
	 * @return value of Genres
	 */
	public final java.lang.String getGenres(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Genres.toString());
	}

	/**
	 * Set value of Genres
	 * @param genres
	 */
	public final void setGenres(java.lang.String genres)
	{
		setGenres(getContext(), genres);
	}

	/**
	 * Set value of Genres
	 * @param context
	 * @param genres
	 */
	public final void setGenres(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String genres)
	{
		getMendixObject().setValue(context, MemberNames.Genres.toString(), genres);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnownForTitles
	 */
	public final imdbtests.proxies.NameBasics getKnownForTitles() throws com.mendix.core.CoreException
	{
		return getKnownForTitles(getContext());
	}

	/**
	 * @param context
	 * @return value of KnownForTitles
	 * @throws com.mendix.core.CoreException
	 */
	public final imdbtests.proxies.NameBasics getKnownForTitles(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imdbtests.proxies.NameBasics result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnownForTitles.toString());
		if (identifier != null) {
			result = imdbtests.proxies.NameBasics.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnownForTitles
	 * @param knownfortitles
	 */
	public final void setKnownForTitles(imdbtests.proxies.NameBasics knownfortitles)
	{
		setKnownForTitles(getContext(), knownfortitles);
	}

	/**
	 * Set value of KnownForTitles
	 * @param context
	 * @param knownfortitles
	 */
	public final void setKnownForTitles(com.mendix.systemwideinterfaces.core.IContext context, imdbtests.proxies.NameBasics knownfortitles)
	{
		if (knownfortitles == null) {
			getMendixObject().setValue(context, MemberNames.KnownForTitles.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnownForTitles.toString(), knownfortitles.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return titleMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imdbtests.proxies.Title that = (imdbtests.proxies.Title) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
