// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbutils.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MxDbUtils module
	public static void dS_GetDatabase(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MxDbUtils.DS_GetDatabase").withParams(params).execute(context);
	}
	public static mxdbutils.proxies.DatabaseInformation dS_GetDatabaseInformation(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MxDbUtils.DS_GetDatabaseInformation").withParams(params).execute(context);
		return result == null ? null : mxdbutils.proxies.DatabaseInformation.initialize(context, result);
	}
	public static mxdbutils.proxies.Query dS_GetQuery(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MxDbUtils.DS_GetQuery").withParams(params).execute(context);
		return result == null ? null : mxdbutils.proxies.Query.initialize(context, result);
	}
	public static void iVK_ExecuteQuery(IContext context, mxdbutils.proxies.Query _query)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Query", _query == null ? null : _query.getMendixObject());
		Core.microflowCall("MxDbUtils.IVK_ExecuteQuery").withParams(params).execute(context);
	}
}
