// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package csvservices.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the CsvServices module

	public static boolean mF_StartCsvServices(IContext context, String _user_Role)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("User_Role", _user_Role);
			return (Boolean)Core.execute(context, "CsvServices.MF_StartCsvServices", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}