// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package csvservices.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the CsvServices module
	public static boolean mF_StartCsvServices(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("CsvServices.MF_StartCsvServices").withParams(params).execute(context);
	}
	public static boolean mF_StartCsvServices_DefaultRole(IContext context, java.lang.String _user_Role)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User_Role", _user_Role);
		return (java.lang.Boolean) Core.microflowCall("CsvServices.MF_StartCsvServices_DefaultRole").withParams(params).execute(context);
	}
}
