// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbutils.proxies;

public enum DatabaseImplementation
{
	PostgreSQL(new java.lang.String[][] { new java.lang.String[] { "en_US", "PostgreSQL" } }),
	SQL_Server(new java.lang.String[][] { new java.lang.String[] { "en_US", "SQL Server" } }),
	Oracle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Oracle" } }),
	MySQL(new java.lang.String[][] { new java.lang.String[] { "en_US", "MySQL" } }),
	HSQLDB(new java.lang.String[][] { new java.lang.String[] { "en_US", "HSQLDB" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private DatabaseImplementation(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
