// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbutils.proxies;

public enum DatabaseImplementation
{
	PostgreSQL(new java.lang.String[][] { new java.lang.String[] { "en_US", "PostgreSQL" } }),
	SQL_Server(new java.lang.String[][] { new java.lang.String[] { "en_US", "SQL Server" } }),
	Oracle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Oracle" } }),
	MySQL(new java.lang.String[][] { new java.lang.String[] { "en_US", "MySQL" } }),
	HSQLDB(new java.lang.String[][] { new java.lang.String[] { "en_US", "HSQLDB" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private DatabaseImplementation(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
