// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbutils.actions;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.function.Function;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Free format update statement.
 * Returns amount of records mutated.
 */
public class ExecuteDatabaseUpdateStatement extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String statement;

	public ExecuteDatabaseUpdateStatement(IContext context, java.lang.String statement)
	{
		super(context);
		this.statement = statement;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Long result = Core.dataStorage().executeWithConnection(getContext(), executeStatement(statement));
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteDatabaseUpdateStatement";
	}

	// BEGIN EXTRA CODE
	private Function<Connection, Long> executeStatement(String sql) throws Exception {
		return connection -> {
			Statement statement = null;
			try {
				statement = connection.createStatement();
				return (long) statement.executeUpdate(sql);
			} catch (Exception e) {
				throw new RuntimeException(e);
			} finally {
				try {
					statement.close();
				} catch (SQLException e) {
					throw new RuntimeException(e);
				}
			}
		};
	}
	// END EXTRA CODE
}
