// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbutils.actions;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.function.Function;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxdbutils.proxies.DatabaseInformation;
import mxdbutils.proxies.Query;
import mxdbutils.proxies.DatabaseImplementation;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetDatabaseInformation extends CustomJavaAction<IMendixObject>
{
	public GetDatabaseInformation(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Core.dataStorage().executeWithConnection(getContext(), getDatabaseInformation(getContext())); 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetDatabaseInformation";
	}

	// BEGIN EXTRA CODE
	
	private Function<Connection, IMendixObject> getDatabaseInformation(IContext context) throws Exception {
		return connection ->
		{
			DatabaseInformation dbInfo = new DatabaseInformation(context);
			try {
				
				DatabaseMetaData dbMeta = connection.getMetaData();
				dbInfo.setProductName(dbMeta.getDatabaseProductName());
				dbInfo.setProductVersion(dbMeta.getDatabaseProductVersion());
				
				switch (dbMeta.getDatabaseProductName()) {
				case "HSQL Database Engine":
					dbInfo.setImplementation(DatabaseImplementation.HSQLDB);
					break;
				case "Microsoft SQL Server":
					dbInfo.setImplementation(DatabaseImplementation.SQL_Server);
					break;
				case "Oracle":
					dbInfo.setImplementation(DatabaseImplementation.Oracle);
					break;
				case "PostgreSQL":
					dbInfo.setImplementation(DatabaseImplementation.PostgreSQL);
					break;
				}
				
			} catch (SQLException e) {
				throw new RuntimeException(e);
			}
			return dbInfo.getMendixObject();
		};
	}
	// END EXTRA CODE
}
